### ISSUE TITLE
Add separate branch for PRs awaiting release

### ISSUE THREAD

**Issue by DDtKey** [dotenv-linter/dotenv-linter.github.io#21]
@dotenv-linter/core what do you think about accepting pull requests in this repository not to the master branch?

Since the master is immediately reflected on the documentation site, we have a lot of PRs that are awaiting release (`wait-release`).
By the time of release, it will take a lot of effort to merge all conflicts, so it is better to merge them in a separate branch beforehand.

Or, if possible, on the contrary, upload the site from another branch 🤔

**Comment by mgrachev** [comment]
Good idea 👍 Thank you 🙏

I have created the `develop` branch.
